# Time-stamp: <2021-06-11 23:19:28 kmodi>

.DEFAULT_GOAL := default

DEFAULT_SV_LIB ?= dummy
FILES ?= *.c *.v *.sv

GIT_ROOT = $(shell git rev-parse --show-toplevel)
include $(GIT_ROOT)/makefile

default: nc
