import nimterop/cimport
import os
from macros import getProjectPath

# static:
#   cDisableCaching()
#   cDebug()

const
  # mean_func_3_64.so is generated by running ./build_script_64.
  includePath = getProjectPath() / "matlab_export"
  soFile = includePath / "mean_func_3_64.so"
static:
  doAssert fileExists(includePath / "mean_func_3.h")
  cAddSearchDir(includePath)

cOverride:
  type
    boolean_T = cuchar # from rtwtypes.h
    emxArray_int32_T* = object
      data*: ptr UncheckedArray[cint] # this pointer needed to be fixed
      size*: ptr UncheckedArray[cint] # this pointer needed to be fixed
      allocatedSize*: cint
      numDimensions*: cint
      canFreeData*: boolean_T

cImport(cSearchPath("mean_func_3_types.h"), recurse=true)

type
  IntArrayObj* = emxArray_int32_T
  ArrWrapObj* = elem_struct_t
  InputObj* = in_struct_t

  ResultsObj* = struct1_T
  OutputObj* = struct0_T

proc mean_func*(inp: ptr InputObj; outp: ptr OutputObj) {.importc: "mean_func_3", dynlib: soFile.}
