/* Generated by Nim Compiler v1.5.1 */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -fmax-errors=3 -DDPI_COMPATIBILITY_VERSION_1800v2012  -fPIC  -Inim/devel/lib -Ib.set_get_scope -o b.set_get_scope/.nimcache/@mlibdpi.nim.c.o b.set_get_scope/.nimcache/@mlibdpi.nim.c */
#define NIM_INTBITS 64

/* section: NIM_merge_HEADERS */

#include "nimbase.h"
#include "/cad/adi/apps/cadence/xlm/linux/20.03-s02/tools.lnx86/inca/include/svdpi.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef far
#undef powerpc
#undef unix

/* section: NIM_merge_FRAME_DEFINES */
  #  define nimfr_(proc, file) \
      TFrame FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = 0; nimFrame(&FR_);

  #  define nimfrs_(proc, file, slots, length) \
      struct {TFrame* prev;NCSTRING procname;NI line;NCSTRING filename; NI len; VarSlot s[slots];} FR_; \
      FR_.procname = proc; FR_.filename = file; FR_.line = 0; FR_.len = length; nimFrame((TFrame*)&FR_);

  #  define nimln_(n, file) \
      FR_.line = n; FR_.filename = file;

/* section: NIM_merge_FORWARD_TYPES */
typedef struct NimStrPayload NimStrPayload;
typedef struct NimStringV2 NimStringV2;

/* section: NIM_merge_TYPES */
struct NimStrPayload {
NI cap;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct NimStringV2 {
NI len;
NimStrPayload* p;
};
typedef NimStringV2 tyArray__nHXaesL0DJZHyVS07ARPRA[1];

/* section: NIM_merge_PROC_HEADERS */
N_LIB_EXPORT N_CDECL(void, f_scopetest_nim)(void);
N_LIB_PRIVATE N_NIMCALL(void, switchToScope__uYVD71pP3N5I2HvOLY7AVA)(svScope newScope);
N_NIMCALL(void, f_scopetest_sv)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw)(void);
static N_INLINE(void, popFrame)(void);
N_NIMCALL(NimStringV2, rawNewString)(NI cap);
static N_INLINE(void, appendString)(NimStringV2* dest, NimStringV2 src);
static N_INLINE(void, copyMem__i80o3k0SgEI5gTRCzYdyWAsystem)(void* dest, void* source, NI size);
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size);
N_LIB_PRIVATE N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NOINLINE(void, raiseRangeErrorI)(NI64 i, NI64 a, NI64 b);
N_LIB_PRIVATE N_NIMCALL(void, prepareAdd)(NimStringV2* s, NI addlen);
N_LIB_PRIVATE N_NIMCALL(void, add__8FwY5enLGB0dFerO6Ny9caw)(NimStringV2* x, NCSTRING y);
N_LIB_PRIVATE N_NIMCALL(void, echoBinSafe)(NimStringV2* args, NI argsLen_0);
N_LIB_PRIVATE N_NIMCALL(void, eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ)(NimStringV2* dest);
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void);
N_LIB_PRIVATE N_NIMCALL(void, nimTestErrorFlag)(void);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_LIB_PRIVATE N_NIMCALL(void, systemDatInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, systemInit000)(void);
N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void);

/* section: NIM_merge_DATA */
static const struct {
  NI cap; NIM_CHAR data[16+1];
} TM__C79c1pNy4IhbEfqBgyHd0UA_2 = { 16 | NIM_STRLIT_FLAG, "origScopeName = " };
static const NimStringV2 TM__C79c1pNy4IhbEfqBgyHd0UA_3 = {16, (NimStrPayload*)&TM__C79c1pNy4IhbEfqBgyHd0UA_2};
static const NimStringV2 TM__C79c1pNy4IhbEfqBgyHd0UA_6 = {16, (NimStrPayload*)&TM__C79c1pNy4IhbEfqBgyHd0UA_2};
static const NimStringV2 TM__C79c1pNy4IhbEfqBgyHd0UA_7 = {16, (NimStrPayload*)&TM__C79c1pNy4IhbEfqBgyHd0UA_2};

/* section: NIM_merge_VARS */
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TFrame* framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
extern NIM_BOOL nimInErrorMode__759bT87luu8XGcbkw13FUjA;

/* section: NIM_merge_PROCS */
static N_INLINE(void, nimFrame)(TFrame* s) {
	{
		if (!(framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw == ((TFrame*) NIM_NIL))) goto LA3_;
		(*s).calldepth = ((NI16) 0);
	}
	goto LA1_;
	LA3_: ;
	{
		(*s).calldepth = (NI16)((*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1));
	}
	LA1_: ;
	(*s).prev = framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA8_;
		callDepthLimitReached__mMRdr4sgmnykA9aWeM9aDZlw();
	}
	LA8_: ;
}
static N_INLINE(void, popFrame)(void) {
	framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr__HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}
N_LIB_PRIVATE N_NIMCALL(void, switchToScope__uYVD71pP3N5I2HvOLY7AVA)(svScope newScope) {
	svScope prevScope;
	nimfr_("switchToScope", "b.set_get_scope/libdpi.nim");
	nimln_(10, "b.set_get_scope/libdpi.nim");
	prevScope = svSetScope(newScope);
	nimln_(13, "b.set_get_scope/libdpi.nim");
	f_scopetest_sv();
	popFrame();
}
static N_INLINE(void, nimCopyMem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}
static N_INLINE(void, copyMem__i80o3k0SgEI5gTRCzYdyWAsystem)(void* dest, void* source, NI size) {
	nimCopyMem(dest, source, size);
}
static N_INLINE(void, appendString)(NimStringV2* dest, NimStringV2 src) {
{	{
		void* T5_;
		void* T6_;
		NI TM__C79c1pNy4IhbEfqBgyHd0UA_4;
		NI TM__C79c1pNy4IhbEfqBgyHd0UA_5;
		if (!(((NI) 0) < src.len)) goto LA3_;
		T5_ = (void*)0;
		T5_ = ((void*) ((&(*(*dest).p).data[(*dest).len])));
		T6_ = (void*)0;
		T6_ = ((void*) ((&(*src.p).data[((NI) 0)])));
		if (nimAddInt(src.len, ((NI) 1), &TM__C79c1pNy4IhbEfqBgyHd0UA_4)) { raiseOverflow(); goto BeforeRet_;
};
		if (((NI)(TM__C79c1pNy4IhbEfqBgyHd0UA_4)) < ((NI) 0) || ((NI)(TM__C79c1pNy4IhbEfqBgyHd0UA_4)) > ((NI) IL64(9223372036854775807))){ raiseRangeErrorI((NI)(TM__C79c1pNy4IhbEfqBgyHd0UA_4), ((NI) 0), ((NI) IL64(9223372036854775807))); goto BeforeRet_;
}
		copyMem__i80o3k0SgEI5gTRCzYdyWAsystem(T5_, T6_, ((NI) ((NI)(TM__C79c1pNy4IhbEfqBgyHd0UA_4))));
		if (nimAddInt((*dest).len, src.len, &TM__C79c1pNy4IhbEfqBgyHd0UA_5)) { raiseOverflow(); goto BeforeRet_;
};
		(*dest).len = (NI)(TM__C79c1pNy4IhbEfqBgyHd0UA_5);
	}
	LA3_: ;
	}BeforeRet_: ;
}
static N_INLINE(NIM_BOOL*, nimErrorFlag)(void) {
	NIM_BOOL* result;
	result = (NIM_BOOL*)0;
	result = (&nimInErrorMode__759bT87luu8XGcbkw13FUjA);
	return result;
}
N_LIB_EXPORT N_CDECL(void, f_scopetest_nim)(void) {
	NimStringV2 fmtRes;
	NimStringV2 fmtRes_2;
	NimStringV2 fmtRes_3;
	svScope scope;
	NCSTRING origScopeName;
	tyArray__nHXaesL0DJZHyVS07ARPRA T2_;
	tyArray__nHXaesL0DJZHyVS07ARPRA T3_;
	tyArray__nHXaesL0DJZHyVS07ARPRA T4_;
NIM_BOOL* nimErr_;
	nimfr_("f_scopetest_nim", "b.set_get_scope/libdpi.nim");
{nimErr_ = nimErrorFlag();
	fmtRes.len = 0; fmtRes.p = NIM_NIL;
	fmtRes_2.len = 0; fmtRes_2.p = NIM_NIL;
	fmtRes_3.len = 0; fmtRes_3.p = NIM_NIL;
	nimln_(17, "b.set_get_scope/libdpi.nim");
	scope = svGetScope();
	nimln_(19, "b.set_get_scope/libdpi.nim");
	origScopeName = svGetNameFromScope(scope);
	nimln_(21, "b.set_get_scope/libdpi.nim");
	switchToScope__uYVD71pP3N5I2HvOLY7AVA(scope);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(22, "b.set_get_scope/libdpi.nim");
	fmtRes = rawNewString(((NI) 41));
	prepareAdd((&fmtRes), 16);
appendString((&fmtRes), TM__C79c1pNy4IhbEfqBgyHd0UA_3);
	nimln_(621, "nim/devel/lib/pure/strformat.nim");
	add__8FwY5enLGB0dFerO6Ny9caw((&fmtRes), origScopeName);
	T2_[0] = fmtRes;
	echoBinSafe(T2_, 1);
	nimln_(25, "b.set_get_scope/libdpi.nim");
	scope = svGetScopeFromName("top.u_other_module");
	nimln_(26, "b.set_get_scope/libdpi.nim");
	switchToScope__uYVD71pP3N5I2HvOLY7AVA(scope);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(27, "b.set_get_scope/libdpi.nim");
	fmtRes_2 = rawNewString(((NI) 41));
	prepareAdd((&fmtRes_2), 16);
appendString((&fmtRes_2), TM__C79c1pNy4IhbEfqBgyHd0UA_6);
	nimln_(621, "nim/devel/lib/pure/strformat.nim");
	add__8FwY5enLGB0dFerO6Ny9caw((&fmtRes_2), origScopeName);
	T3_[0] = fmtRes_2;
	echoBinSafe(T3_, 1);
	nimln_(30, "b.set_get_scope/libdpi.nim");
	scope = svGetScopeFromName(origScopeName);
	nimln_(31, "b.set_get_scope/libdpi.nim");
	switchToScope__uYVD71pP3N5I2HvOLY7AVA(scope);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	nimln_(32, "b.set_get_scope/libdpi.nim");
	fmtRes_3 = rawNewString(((NI) 41));
	prepareAdd((&fmtRes_3), 16);
appendString((&fmtRes_3), TM__C79c1pNy4IhbEfqBgyHd0UA_7);
	nimln_(621, "nim/devel/lib/pure/strformat.nim");
	add__8FwY5enLGB0dFerO6Ny9caw((&fmtRes_3), origScopeName);
	T4_[0] = fmtRes_3;
	echoBinSafe(T4_, 1);
	{
		LA1_:;
	}
	{
		nimln_(53, "nim/devel/lib/system/fatal.nim");
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&fmtRes_3));
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&fmtRes_2));
		eqdestroy___dS1BF3Vxjg9aJMmmhVJKSpQ((&fmtRes));
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
}
static N_INLINE(void, initStackBottomWith)(void* locals) {
}

N_LIB_PRIVATE void PreMainInner(void) {
}

N_LIB_PRIVATE int cmdCount;
N_LIB_PRIVATE char** cmdLine;
N_LIB_PRIVATE char** gEnv;
N_LIB_PRIVATE void PreMain(void) {
	void (*volatile inner)(void);
	inner = PreMainInner;
	systemDatInit000();
	systemInit000();
	(*inner)();
}

N_LIB_PRIVATE N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_LIB_EXPORT N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

N_LIB_PRIVATE void NIM_POSIX_INIT NimMainInit(void) {
	NimMain();
}

N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {
{
}
}
