/* MTI_DPI */

/*
 * Copyright 2002-2013 Mentor Graphics Corporation.
 *
 * Note:
 *   This file is automatically generated.
 *   Please do not edit this file - you will lose your edits.
 *
 * Settings when this file was generated:
 *   PLATFORM = 'linux'
 */
#ifndef INCLUDED_RISK
#define INCLUDED_RISK

#ifdef __cplusplus
#define DPI_LINK_DECL  extern "C" 
#else
#define DPI_LINK_DECL 
#endif

#include "svdpi.h"



DPI_LINK_DECL DPI_DLLESPEC
int
C_dsp(
    int p0);

DPI_LINK_DECL DPI_DLLESPEC
int
C_risc(
    int p0);

DPI_LINK_DECL void
V_init_mem(
    int A,
    int D);

DPI_LINK_DECL int
V_posedge();

DPI_LINK_DECL int
V_read(
    int address,
    int* data);

DPI_LINK_DECL int
V_write(
    int address,
    int data);

#endif 
