
all:
	cd abstraction-reuse/; make 
	cd external-model/; make 
	cd golden/; make 
	cd software/; make 
	cd user-interface/; make tools; make
	cd utility-library/; make 
	cd vector-file/; make 

clean:
	cd abstraction-reuse/; make clean
	cd external-model/; make clean
	cd golden/; make clean
	cd software/; make clean
	cd user-interface/; make clean
	cd utility-library/; make clean
	cd vector-file/; make clean

cleanall:
	cd abstraction-reuse/; make cleanall
	cd external-model/; make cleanall
	cd golden/; make cleanall
	cd software/; make cleanall
	cd user-interface/; make cleanall
	cd utility-library/; make cleanall
	cd vector-file/; make cleanall

tools:
	cd user-interface; make tools
	cd vector-file; make tools
