import os
from macros import getProjectPath

const
  # mean_func_1_64.so is generated by running ./build_script_64.
  soFile = getProjectPath() / "matlab_export" / "mean_func_1_64.so"

type
  Boolean* = cuchar

  DataObj* = object
    data*: ptr UncheckedArray[cint]
    size*: ptr UncheckedArray[cint]
    allocatedSize*: cint
    numDimensions*: cint
    canFreeData*: Boolean
  DataObjRef* = ref DataObj

  # struct0_T
  InputObj* = object
    data*: DataObjRef
    Len*: cint # length of data.data[]
  InputObjRef* = ref InputObj

  # struct1_T
  OutputObj* = object
    mean*: cdouble
    Max*: cint
    Min*: cint
  OutputObjRef* = ref OutputObj

proc mean_func_1*(inp: InputObjRef; outp: OutputObjRef) {.importc, dynlib: soFile.}
