import nimterop/cimport
import os
from macros import getProjectPath

# static:
#   cDisableCaching()
#   cDebug()

const
  # mean_func_2_64.so is generated by running ./build_script_64.
  includePath = getProjectPath() / "matlab_export"
  soFile = includePath / "mean_func_2_64.so"
static:
  doAssert fileExists(includePath / "mean_func_2.h")
  cAddSearchDir(includePath)

cImport(cSearchPath("mean_func_2.h"), recurse=true)

type
  InputObj* = struct0_T
  # InputObjRef* = ref InputObj

  OutputObj* = struct1_T
  OutputObjRef* = ref OutputObj

proc mean_func*(inp: array[4, InputObj]; outp: OutputObjRef) {.importc: "mean_func_2", dynlib: soFile.}
